// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsmifehyp13PvnufiKmqFisGWZpt7LZkM',
    appId: '1:489857285870:web:325cae713c76ebd5bf7dff',
    messagingSenderId: '489857285870',
    projectId: 'gakuyoumatch',
    authDomain: 'gakuyoumatch.firebaseapp.com',
    storageBucket: 'gakuyoumatch.firebasestorage.app',
    measurementId: 'G-6HG1BFTGLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7k66rC2919c5A-Bfl8CFUcRLKzzNWnm0',
    appId: '1:489857285870:android:4ca232d2df1e88c3bf7dff',
    messagingSenderId: '489857285870',
    projectId: 'gakuyoumatch',
    storageBucket: 'gakuyoumatch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjtHAorWbFc7FIYChozoV59qgutRdAWnc',
    appId: '1:489857285870:ios:42c156be0591d89fbf7dff',
    messagingSenderId: '489857285870',
    projectId: 'gakuyoumatch',
    storageBucket: 'gakuyoumatch.firebasestorage.app',
    iosBundleId: 'com.example.gakuyoumatch2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjtHAorWbFc7FIYChozoV59qgutRdAWnc',
    appId: '1:489857285870:ios:42c156be0591d89fbf7dff',
    messagingSenderId: '489857285870',
    projectId: 'gakuyoumatch',
    storageBucket: 'gakuyoumatch.firebasestorage.app',
    iosBundleId: 'com.example.gakuyoumatch2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsmifehyp13PvnufiKmqFisGWZpt7LZkM',
    appId: '1:489857285870:web:25f02cf282ab2d74bf7dff',
    messagingSenderId: '489857285870',
    projectId: 'gakuyoumatch',
    authDomain: 'gakuyoumatch.firebaseapp.com',
    storageBucket: 'gakuyoumatch.firebasestorage.app',
    measurementId: 'G-54PS00E7K4',
  );

}